### ISSUE TITLE
Unused variable in lr1110_gnss_get_context_status

### ISSUE THREAD

**Issue by ncasaril** [Lora-net/lr1110_driver#10]
https://github.com/Lora-net/lr1110_driver/blob/764b9744ef0fd4610a9757037a0b8900afc2e065/src/lr1110_gnss.c#L595

**Comment by matthieuantoine** [comment]
HI @ncasaril!

Thanks for reporting this issue. It will be fixed in the next delivery.

**Comment by matthieuantoine** [comment]
Fixed in release v4.0.0 (see c7ce58c5fecaf0b7997478bd446f3cfce4891f72)
