### ISSUE TITLE
NAV payload

### ISSUE THREAD

**Issue by laurent-latorre** [Lora-net/lr1110_driver#11]
Hello,
Is the GNSS scan response payload documented somewhere ?
I basically need to recover pseudorange values for all sat in view in the scan result but I can't find the payload parsing approach.
Thanks for your help !

**Comment by TeslaK20** [comment]
Does anyone know the answer to this? Please?

**Comment by TeslaK20** [comment]
Surely some of you have worked with this radio - is there any knowledge whatsoever about the format of the NAV file?

**Comment by matthieuantoine** [comment]
Hi, the content of the NAV payload is not public.

**Comment by induthings-coder** [comment]
Dear All, we are having the same issue, beacuse we need to solve location on-premise. Any news?
