### ISSUE TITLE
Error in GNSS scanning

### ISSUE THREAD

**Issue by kvkc97** [Lora-net/lr1110_driver#15]
I am trying to implement GNSS Scanning currently and having some issues.
I have used the following commands for the GNSS scan.

GNSSSetConstellationToUse() to set GPS constellation. This command was successfully executed in the IC.
GnssSetMode() to set single scanning option. The value of Stat 1 and Stat2 registers after this command were 6 and 0 respectively. Is it a valid response? (Stat 2 register was never 0 for any other command)
GnssAutonmous() with the following arguments. The value of Stat1 register was 3. I crosschecked the implemented but couldnot find an error in it. The GNSS Done interrupt flag was set after this command but the size of result was obtained as 0.
![image](https://user-images.githubusercontent.com/73599382/128226133-5b0690e0-acd7-44ce-8980-754ec822a71c.png)

I have attached the implemented code for 2. and 3. below. Could you please suggest what went wrong.
![image](https://user-images.githubusercontent.com/73599382/128226106-5d3e7725-b489-456a-ab30-2f78e7295ecc.png)

@gianni2996 Could you help with this issue.

**Comment by kvkc97** [comment]
Can I get a solution for this issue.

**Comment by gianni2996** [comment]
Hi @kvkc97, can I see also the code where you return the results of the scan? Thanks

**Comment by kvkc97** [comment]
To check the results I have two functions, GnssGetNbSvDetected() and GnssGetResultSize(). The result size is returning value 2 while number of satellites is 0. I have attached the  implementing codes below.
![image](https://user-images.githubusercontent.com/73599382/130361929-8e951a4f-a2e3-426d-bbc7-e202e8c7125f.png)
GnssGetNbSvDetected() function
![image](https://user-images.githubusercontent.com/73599382/130361939-25ab09da-6b3f-43de-a52f-8f672260b014.png)
GnssGetResultSize() function
![image](https://user-images.githubusercontent.com/73599382/130361958-a7dc1ba3-80f5-4045-804f-db404db91ceb.png)

**Comment by matthieuantoine** [comment]
Several questions:

- What is the version of the firmware you are using?
- What is the version of the driver you are using?
- Do you check the status returned by the functions before processing the out parameters?

**Comment by kvkc97** [comment]
HW Version of LR1110 = 34
FW Version of LR1110 = 03.03

I checked the value of status register after each command once more now. After set_scan command, the status register values are 6 and  respectively. After scan command, the GNSS_DONE interrupt is  generated and stat1 value shows the last command was succesfully executed. Stat2 value is 19. The Stat1 and Stat2 values are 4 and 19 for all other commands. However, no results is obtained in the number of satellites detected.

**Comment by gianni2996** [comment]
Supposing that you are using the modem version driver, you have to use the get_event_size() and get_event() functions on the interrupt firing, in order to retrieve the size and the results, for me it works.  Notice that if you call the get_event(), the function get_event_size() is already called inside the get_event(), so you don't have to call it twice or maybe you can have some problems as I experienced.

**Comment by matthieuantoine** [comment]
@gianni2996 - according to the FW version shared by @kvkc97, he is running a transceiver.

Let me try to reproduce the exact same sequence with the same firmware version.

**Comment by kvkc97** [comment]
@matthieuantoine Were you able to find the problem? And yes I am running in transceiver mode.
