### ISSUE TITLE
LR1110 LoRa transmission

### ISSUE THREAD

**Issue by kvkc97** [Lora-net/lr1110_driver#16]
I have been to communicate LR1110 IC with a gateway with LoRaWAN protocol. After setting the parameters as per LR1110 User Manual, i used set_tx function to transmit. The packet is received at the gateway however there is an error occuring that PLL did not lock. I tried changing the frequency and used calibrate() with calibparam value 0x24 but error still exists. How to solve it?

Also could you please suggest a LoRaWAN Stack to be used for further development.

**Comment by matthieuantoine** [comment]
Can you please share the configuration of the board you are using? Do you have a TCXO?

Concerning the LoRaWAN stack, you can have a look at https://github.com/Lora-net/LoRaMac-node

**Comment by kvkc97** [comment]
![image](https://user-images.githubusercontent.com/73599382/130363448-ea50ec65-66a6-4390-9f72-b079925ca4e8.png)
![image](https://user-images.githubusercontent.com/73599382/130363474-b1884f98-de1a-4deb-b5be-936a0970279a.png)
![image](https://user-images.githubusercontent.com/73599382/130363495-c88cd150-ca6e-4b81-b9ee-805fdea6ce04.png)
![image](https://user-images.githubusercontent.com/73599382/130363532-3ef2c689-b307-4d36-9851-dc991426a0b8.png)
I have attached the code snippet of LR1110 configuration. TCXO is not used in this case although provision is provided in the schematic. LR1110 interface in schematic is also attached.
[Schematic-2.pdf](https://github.com/Lora-net/lr1110_driver/files/7027787/Schematic-2.pdf)

**Comment by matthieuantoine** [comment]
Where did you spot the error stating that the PLL did not lock?

Some comments:

- it is recommended to set the packet type before you configure the RF frequency
- the value assigned to `rbu` is incompatible with its type

**Comment by kvkc97** [comment]
PLL lock error is obtained after set_tx function. I have checked for errors after each functions and no error was obtained. 

I changed the flow to call set packet type before configuring the RF frequency, but same error is obtained.

 I have also inserted MAC layer code from https://github.com/Lora-net/LoRaMac-node and send Join Request function also. The Request is correctly detected at the server and Accept is also generated however PLL error is still there.

**Comment by kvkc97** [comment]
Hi,

Any update on this issue. Also, is there a need to switch to FS as intermediate mode while switch from TX to RX and vice versa while using auto tx rx mode.

I was testing for LoRa transmission with LR1110 IC in OTA mode using LoRaMAC code. The Join request is successfully sent to the server and Join accept is generated from the server and is passed to the gateway. The gateway also forwards the packet. However the packet is not received at the end device (custom board developed using STM32 controller). I have attached the Join request and join accept messages. 
The IC is going to rx mode after transmitting but packet is not received. At time the IC goes to busy after TX mode and gets stuck. At times it goes to RX mode. A few times when in RX mode, interrupt for preamble detection is generated but no further packet is received and most of the times preamble detection also is not done. What would be the issue? Is it due to the PLL error generated.
Join request at server
![Join Req](https://user-images.githubusercontent.com/73599382/132042241-46486dad-3795-4367-aa39-0c9a6f57a49e.JPG)
Join accept at server
![Join Accept](https://user-images.githubusercontent.com/73599382/132042221-9f9d4487-2323-4f0f-9f9c-4dd89fd80f52.JPG)
Join request and Join Request at gateway
![image](https://user-images.githubusercontent.com/73599382/132200958-75ef0512-af11-4a7d-89b3-678d1a7bafe1.png)

**Comment by kvkc97** [comment]
Can I have an update on this

**Comment by matthieuantoine** [comment]
> Also, is there a need to switch to FS as intermediate mode while switch from TX to RX and vice versa while using auto tx rx mode.

No, there is not. The chip takes care of the state transitions.

**Comment by matthieuantoine** [comment]
It seems that you introduced another topic with your last message - related to LoRaMAC node.

Can you please open an issue in the dedicated repository?

**Comment by MagnusErler** [comment]
@kvkc97 Can you share your solution for joining a Lora network. What I'm seeing from your code, is that you are setting the parameters to Lora and then just sending a command. When are you joining the network?
