### ISSUE TITLE
Error in integrating LoRaMAC node and LR1110 Driver

### ISSUE THREAD

**Issue by kvkc97** [Lora-net/lr1110_driver#19]
I was testing for LoRa transmission with LR1110 IC in OTA mode using LoRaMAC code. The Join request is successfully sent to the server and Join accept is generated from the server and is passed to the gateway. The gateway also forwards the packet. However the packet is not received at the end device (custom board developed using STM32 controller). I have attached the Join request and join accept messages.
The IC is going to rx mode after transmitting but packet is not received. At time the IC goes to busy after TX mode and gets stuck. At times it goes to RX mode. A few times when in RX mode, interrupt for preamble detection is generated but no further packet is received and most of the times preamble detection also is not done. What would be the issue? Is it due to the PLL error generated.
Join request at server
![image](https://user-images.githubusercontent.com/73599382/132337724-8903a1c0-b94b-4a3a-8cec-f5f208563bc3.png)
Join accept at server
![image](https://user-images.githubusercontent.com/73599382/132337764-f99b13ff-b7f0-452b-bbb0-b763d844e76b.png)
Join request and Join Request at gateway
![image](https://user-images.githubusercontent.com/73599382/132337881-96972b57-dec1-4caa-857b-4f73af97b450.png)

**Comment by matthieuantoine** [comment]
Can you please check that Rx windows are timely open? If you miss the beginning of the packet, the reception cannot be performed.

**Comment by kvkc97** [comment]
Yes I checked that. The RX windows are opened correctly.

**Comment by matthieuantoine** [comment]
> At time the IC goes to busy after TX mode and gets stuck

Can you please define `stuck`?

I think that a logical trace would help to catch issue.

**Comment by kvkc97** [comment]
Before sending a command to the IC the busy pin values is checked to see if the IC is busy or not. After TX mode sometimes the busy pin value of the IC remains high. So IC is always busy and the program is stuck.

Also how to remove the PLL error after set_tx command

**Comment by kvkc97** [comment]
The firmware version in LR1110 is 0303. Is this version compatible with LR1110 Version1.0.0. If not, how can I change the firmware version of LR1110? Is it possible using SPI?

**Comment by Pirakutu** [comment]
I have it running on version 0303 with the driver version 1.0.0, but i also had this busy pin problem. 

I rewrote the function to include a timeout so it doesnt get stuck for ever. However, i only had this happened to me when i turned the LR1110 on and off (took power away) between messages and only at certain times (not really reproducible). The cases where i left the the device powered from the beginning, were never a problem.

**Comment by kvkc97** [comment]
I added the timeout and code does get stuck there. However, I still cannot receive the packet and PLL error is still there.
