### ISSUE TITLE
Lora transmission happens only in SF7 and SF8

### ISSUE THREAD

**Issue by kvkc97** [Lora-net/lr1110_driver#20]
I am working on LR1110 in IN865 in ABP mode. Data transmission is successful in SF7 and SF8 but not in other spreading factors. The size of the packet is 17 bytes and adr is turned off. Frequency of transmission is 865062500. What can be issue for other spreading factors?

**Comment by kvkc97** [comment]
Can anyone update this issue

**Comment by matthieuantoine** [comment]
> I am working on LR1110 in IN865 in ABP mode

Are you referring to the [LoRaMAC node](https://github.com/Lora-net/LoRaMac-node) project?

**Comment by kvkc97** [comment]
> > Are you referring to the [LoRaMAC node](https://github.com/Lora-net/LoRaMac-node) project?

Yes

**Comment by matthieuantoine** [comment]
In this case, can you please open an issue in the LoRaMAC node project?

**Comment by mluis1** [comment]
Please do not create an issue. Do create a new discussion topic under https://github.com/Lora-net/LoRaMac-node/discussions
