### ISSUE TITLE
Usage example with LoRaMac stack?

### ISSUE THREAD

**Issue by Sensative-Lars-Mats** [Lora-net/lr1110_driver#21]
Is there any example on how to use this LR1110 driver with the semtech LoRaMac stack?

**Comment by matthieuantoine** [comment]
Hi @Sensative-Lars-Mats,

If you are referring to LoRaMAC-node, the LR1110 is supported from [v4.4.4](https://github.com/Lora-net/LoRaMac-node/blob/master/CHANGELOG.md#444---2020-05-26).

> Also using the GNSS functionality with the same?

Can you please elaborate?

**Comment by Sensative-Lars-Mats** [comment]
It seems the examples on github only use the Basics Modem stack but we invested a lot on the LoRaMax stack which also supports this stack from 4.4 approximately. So we need some info on how to use the GNSS part of the driver.

**Comment by Sensative-Lars-Mats** [comment]
Note: we expect to use the https://www.loracloud.com/documentation/geolocation?url=gettingstarted.html#gnss-based-location-estimates-for-lr1110-transceivers on the other end...
