### ISSUE TITLE
LR1110 Firmware update using SPI command

### ISSUE THREAD

**Issue by sohaibqamar** [Lora-net/lr1110_driver#23]
Hi, 
I am using the latest driver for LR1110 in NRF9160 development. My SPI is working fine, I am able to do passive Wi-Fi Scanning and get APs MAC addresses.
The chipset is returning below firmware and hardware version after calling 
`lr_status = lr1110_system_get_version(dev, &lrVer);`
`if(lr_status == LR1110_STATUS_OK) {`
`printk("HW: %u, Type: %u, FW: %u\n\n", lrVer.hw, lrVer.type, (unsigned int)lrVer.fw);`
`}`
`else {`
`printk("Error\n");`
`}`

_Output: HW: 34, Type: 1, FW: 771_

I am trying to update the firmware of the LR1110 chipset using **[lr1110_updater_tool](https://github.com/Lora-net/lr1110_updater_tool)**
Below is the code I am trying to update 

`void main(void)
{

	lr1110_fw_update_status_t status = LR1110_FW_UPDATE_ERROR;
    bool is_updated = false;

	printk("LR1110 Firmware Update.\n");
    k_sleep(K_MSEC(5000));
	setup_spim();
    test_SPIM();
    k_sleep(K_MSEC(5000));
	lr_status = lr1110_hal_reset(dev);
	if(lr_status != LR1110_HAL_STATUS_OK)
		printk("Reset Error!.\n");
	if( LR1110_FIRMWARE_UPDATE_TO == LR1110_FIRMWARE_UPDATE_TO_TRX )
    {
        printk( "Update to transceiver firmware 0x%04x\n", LR1110_FIRMWARE_VERSION );
    }
    else
    {
        printk( "Update to modem firmware 0x%04x\n", LR1110_FIRMWARE_VERSION );
    }
	k_sleep(K_MSEC(5000));
	 while( 1 )
    {
        if( is_updated == false )
        {
            status = lr1110_update_firmware( dev, LR1110_FIRMWARE_UPDATE_TO, LR1110_FIRMWARE_VERSION,
                                             lr1110_firmware_image, ( uint32_t ) LR1110_FIRMWARE_IMAGE_SIZE );

            is_updated = true;
        }
        switch( status )
        {
        case LR1110_FW_UPDATE_OK:
            printk( "UPDATE DONE!\nPlease flash another application\n(like EVK Demo App)\n" );
            break;
        case LR1110_FW_UPDATE_WRONG_CHIP_TYPE:
            printk( "WRONG CHIP TYPE\n" );
            break;
        case LR1110_FW_UPDATE_ERROR:
            printk( "ERROR\nWrong firmware version\nPlease retry\n" );
            break;
        }
		k_sleep(K_MSEC(3000));
    }
}`

Below is my hal function for **lr1110_update_firmware()**

`lr1110_fw_update_status_t lr1110_update_firmware( void* radio, lr1110_fw_update_t fw_update_direction,
                                                  uint32_t fw_expected, const uint32_t* buffer, uint32_t length )
{

    lr1110_fw_update_status_t   status             = LR1110_FW_UPDATE_ERROR;
    lr1110_bootloader_version_t version_bootloader = { 0 };

    lr1110_system_stat1_t stat1;
    lr1110_system_stat2_t stat2;
    uint32_t              irq;

    printk( "Reset the chip...\n" );

    //system_gpio_init_direction_state( lr1110_busy, SYSTEM_GPIO_PIN_DIRECTION_OUTPUT, SYSTEM_GPIO_PIN_STATE_LOW );

    lr1110_system_reset( radio );

    k_sleep(K_MSEC(500));
    //system_gpio_init_direction_state( lr1110_busy, SYSTEM_GPIO_PIN_DIRECTION_INPUT, SYSTEM_GPIO_PIN_STATE_LOW );
    k_sleep(K_MSEC(100));

    printk( "> Reset done!\n" );

    lr1110_bootloader_get_version( radio, &version_bootloader );
    printk( "Chip in bootloader mode:\n" );
    printk( " - LR1110 TYPE = 0x%02X (0xDF for production)\n", version_bootloader.type );
    printk( " - LR1110 HW   = 0x%02X (0x20 for V2A, 0x21 for V2B, 0x22 for V2C)\n", version_bootloader.hw );

    if( version_bootloader.type == 0x01 )
    {
        //system_gpio_set_pin_state( lr1110_led_scan, SYSTEM_GPIO_PIN_STATE_HIGH );

        printk( "Start flash erase...\n" );
        lr1110_bootloader_erase_flash( radio );
        printk( "> Flash erase done!\n" );

        lr1110_bootloader_pin_t      pin      = { 0x00 };
        lr1110_bootloader_chip_eui_t chip_eui = { 0x00 };
        lr1110_bootloader_join_eui_t join_eui = { 0x00 };

        lr1110_bootloader_read_pin( radio, pin );
        lr1110_bootloader_read_chip_eui( radio, chip_eui );
        lr1110_bootloader_read_join_eui( radio, join_eui );

        printk( "PIN is     0x%02X%02X%02X%02X\n", pin[0], pin[1], pin[2], pin[3] );
        printk( "ChipEUI is 0x%02X%02X%02X%02X%02X%02X%02X%02X\n", chip_eui[0], chip_eui[1], chip_eui[2], chip_eui[3],
                chip_eui[4], chip_eui[5], chip_eui[6], chip_eui[7] );
        printk( "JoinEUI is 0x%02X%02X%02X%02X%02X%02X%02X%02X\n", join_eui[0], join_eui[1], join_eui[2], join_eui[3],
                join_eui[4], join_eui[5], join_eui[6], join_eui[7] );
        printk( "Start flashing firmware...\n" );

        lr1110_bootloader_write_flash_encrypted_full( radio, 0, buffer, length );

        printk( "> Flashing done!\n" );

        //system_gpio_set_pin_state( lr1110_led_scan, SYSTEM_GPIO_PIN_STATE_LOW );

        printk( "Rebooting...\n" );
        lr1110_bootloader_reboot( radio, false );
        printk( "> Reboot done!\n" );

        switch( fw_update_direction )
        {
        case LR1110_FIRMWARE_UPDATE_TO_TRX:
        {
            lr1110_system_version_t version_trx = { 0x00 };
            lr1110_system_uid_t     uid         = { 0x00 };

            lr1110_system_get_version( radio, &version_trx );
            printk( "Chip in transceiver mode:\n" );
            printk( " - LR1110 TYPE = 0x%02X\n", version_trx.type );
            printk( " - LR1110 HW   = 0x%02X\n", version_trx.hw );
            printk( " - LR1110 FW   = 0x%04X\n", version_trx.fw );

            lr1110_system_read_uid( radio, uid );

            if( version_trx.fw == fw_expected )
            {
                status = LR1110_FW_UPDATE_OK;
                printk( "Expected firmware running!\n" );
                printk( "Please flash another application (like EVK Demo App).\n" );
                //system_gpio_set_pin_state( lr1110_led_rx, SYSTEM_GPIO_PIN_STATE_HIGH );
            }
            else
            {
                status = LR1110_FW_UPDATE_ERROR;
                printk( "Error! Wrong firmware version - please retry.\n" );
                //system_gpio_set_pin_state( lr1110_led_tx, SYSTEM_GPIO_PIN_STATE_HIGH );
            }
            break;
        }
        case LR1110_FIRMWARE_UPDATE_TO_MODEM:
        {
            lr1110_modem_version_t version_modem = { 0 };
			
            //system_time_wait_ms( 2000 );
            k_sleep(K_MSEC(2000));
            
            lr1110_modem_get_version( radio, &version_modem );
            printk( "Chip in modem mode:\n" );
            printk( " - LR1110 BOOTLOADER = 0x%08x\n", version_modem.bootloader );
            printk( " - LR1110 FW         = 0x%08x\n", version_modem.firmware );
            printk( " - LR1110 LORAWAN    = 0x%04x\n", version_modem.lorawan );

            /*uint32_t fw_version = ( ( uint32_t )( version_modem.functionality ) << 24 ) + version_modem.firmware;

            if( fw_version == fw_expected )
            {
                status = LR1110_FW_UPDATE_OK;
                printk( "Expected firmware running!\n" );
                printk( "Please flash another application (like EVK Demo App).\n" );
                //system_gpio_set_pin_state( lr1110_led_rx, SYSTEM_GPIO_PIN_STATE_HIGH );
            }
            else
            {
                status = LR1110_FW_UPDATE_ERROR;
                printk( "Error! Wrong firmware version - please retry.\n" );
                //system_gpio_set_pin_state( lr1110_led_tx, SYSTEM_GPIO_PIN_STATE_HIGH );
            }*/
            break;
        }
        }
    }
    else
    {
        printk( "Wrong chip type!\n" );
        //system_gpio_set_pin_state( lr1110_led_tx, SYSTEM_GPIO_PIN_STATE_HIGH );
        status = LR1110_FW_UPDATE_WRONG_CHIP_TYPE;
    }

    return status;
}`

The output I am getting.

![image](https://user-images.githubusercontent.com/12796461/148226698-1d6cbfc5-17a3-4ab5-ad6d-ae6f91a2f452.png)

Thank you for reading all the way down. 
Any help would be really appreciated.
--
Regards
Sohaib

**Comment by matthieuantoine** [comment]
See https://github.com/Lora-net/lr1110_updater_tool/issues/4
