### ISSUE TITLE
HAL code example for STM32WB55RGV6 IC 

### ISSUE THREAD

**Issue by kvkc97** [Lora-net/lr1110_driver#5]
I want to interface LR1110 with ARM Cortex M4 microcontroller STM32WB55RGV6 using mbed os. The below mentioned hal functions are not defined in the lora driver code.
lr1110_hal_read
lr1110_hal_write
lr1110_hal_reset
lr1110_hal_wakeup
lr1110_hal_write_read
Is there any example or reference code which can be used using the lora driver code for the mentioned controller.

**Comment by mverdy** [comment]
Hi @kvkc97!

The only references as of today are the one on STM32L476RG https://github.com/Lora-net/lr1110_driver/wiki/Code-snippets or there https://github.com/Lora-net/lr1110_evk_demo_app/blob/master/embedded/application/src/lr1110_hal.c.

Porting this code to the STM32WB55 should be pretty straightforward with the LL drivers. However, are you looking specifically for mbed os library based implementation? I think the basic points you may focus on to port on the mbed library is the control of the SPI, the control of the NSS GPIO, the reading of the BUSY GPIO, and the handling of the IRQ GPIO pin. You will also need the `wait` function in the `reset` and `wakeup` functions.
