### ISSUE TITLE
Plans to translate it to Arduino 

### ISSUE THREAD

**Issue by neilor-mendes** [Lora-net/lr1110_driver#6]
Hello All,

Do you guys have any plans to translate the LR1110 drivers to arduino? What is the roadmap for the drivers?

**Comment by matthieuantoine** [comment]
Hi,

This driver is actually platform-agnostic. As written in the [README file](https://github.com/Lora-net/lr1110_driver/blob/master/README.md), there are 5 HAL functions to implement to make it compatible with your platform:
* lr1110_hal_reset
* lr1110_hal_wakeup
* lr1110_hal_write
* lr1110_hal_read
* lr1110_hal_write_read

An implementation example can be found [here](https://github.com/Lora-net/lr1110_evk_demo_app/blob/master/embedded/application/src/lr1110_hal.c).

Modifications will happen in the following cases:
* A bug is found
* A function is updated
* A new function / feature is implemented

As of today, there is no release planned.
