### ISSUE TITLE
Issue with lora TX power in high power mode

### ISSUE THREAD

**Issue by chegewara** [Lora-net/lr1110_driver#7]
Since there is no response on forum i decided to raise LR1110 firmware issue here.

https://lora-developers.semtech.com/knowledge-base/forum/viewthread/407/

**Comment by matthieuantoine** [comment]
According to the user manual (see §9.5.2), `-9 dBm (0xF7) to +22 dBm(0x16) by step of 1 dB if the High Power PA is selected`.

It means that setting `TxPower` to a value lower than -9dBm is forbidden when using the High Power PA is selected.

**Comment by chegewara** [comment]
Oh, i have to miss it. In that case this issue is not issue and can be closed.

Thanks, and sorry
