### ISSUE TITLE
Radio driver

### ISSUE THREAD

**Issue by gianni2996** [Lora-net/lr1110_driver#9]
Hi,
Sorry if this isn't the right place to make these questions but I did not find this topic anywhere else. I am developing my own application with lr1110 develpement board (with nucleo L476RG).  Until now i send the scanning results through a python script to lora cloud to receive back de geolocation of the device. Now i have a SX1308 picocell gateway, and i'm trying to communicate with it putting LR1110 in tx mode and sending messages, but with no results. I am new to this type of applications and i am a little bit in difficulty to solve this problem, i don't find any guide in the web. It is possible to do it with the tranceiver driver version or I have to use the modem drivers? Maybe am I missing something crucial? 
Thank you in advance

**Comment by matthieuantoine** [comment]
Hello @gianni2996!

To send data through a SX1308 picocell gateway (or any other LoRaWAN gateway), you need to follow the LoRaWAN protocol (sync word, messages, payload, encryption etc.) as defined by the LoRa Alliance. It means that you need to have a LoRaWAN stack running on your end-device.

In your case, you can update your LR1110 into a LoRa Basics Modem-E (updater tool and related information available [here](https://github.com/Lora-net/lr1110_updater_tool)). This firmware integrates a LoRaWAN stack and presents an API that allows you to establish a connection with a LoRaWAN network and send messages. You can find a lot of useful information [here](https://lora-developers.semtech.com/resources/tools/lora-basics/lora-basics-for-end-nodes/developer-walk-through/?url=devices/device_basics_modem_e.html).
